### ISSUE TITLE
messageEnvelope is null

### ISSUE THREAD

**Issue by dsparkplug** [OctopusDeploy/Halibut#157]
### Team

- [X] I've assigned a team label to this issue

### What happened?

After upgrading from v4.4.793 to v4.5.8, we are getting a `messageEnvelope is null` error when sending a Halibut request. Any ideas what could be the cause of this error?

### Reproduction

This happens when we call a method with the following signature:

`public void OnMessageList(Guid asyncCallId, IList<Message> messageList, bool processImmediately = false)`

The public properties of Message are:

- 	`long Id`
- 	`long? ParentId`
- 	`MessageStatusType MessageType` 
- 	`string Text`
- 	`DateTime? TimeStamp`
- 	`bool? AdditionalMessagesExist`
- 	`bool? TailCountPlusMessagesExist`
- 	`int Depth`
- 	`bool IsExternal `

where `MessageStatusType` is an enum.

### Error and Stacktrace

```shell
An error occurred when sending a request to 'https://servername:9000/', after the request began: messageEnvelope is null

   at Halibut.Transport.SecureListeningClient.HandleError(Exception lastError, Boolean retryAllowed)
   at Halibut.Transport.SecureListeningClient.ExecuteTransaction(ExchangeAction protocolHandler, CancellationToken cancellationToken)
   at Halibut.HalibutRuntime.SendOutgoingHttpsRequest(RequestMessage request, CancellationToken cancellationToken)
   at Halibut.HalibutRuntime.<SendOutgoingRequestAsync>d__44.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Halibut.HalibutRuntime.SendOutgoingRequest(RequestMessage request, CancellationToken cancellationToken)
   at Halibut.ServiceModel.HalibutProxy.Invoke(MethodInfo targetMethod, Object[] args)
   at generatedProxy_2.OnMessageList(Guid , IList`1 , Boolean )
```

### Workaround

Downgrade to v4.4.793

**Comment by dsparkplug** [comment]
Issue was fixed by using List instead of IList
